### ISSUE TITLE
Document how to clone an external without checking out that external's git submodules

### ISSUE THREAD

**Issue by christopherwharrop-noaa** [bandre-ucar/manage_externals#164]
### Summary of Issue:
In some cases it is desirable to have a shallow checkout of an external.  For example, when an external contains git submodules which point to other repositories that are not necessary for the top-level application and also are not publicly accessible. In such cases the ability to turn off the recursive git submodule check out of the unneeded/inaccessible repositories would enable use of the external for public applications.   See https://github.com/NOAA-EMC/GSI for an example.  A shallow clone of this repository is needed as an external in other public applications, and is useful in other applications even without it's publicly inaccessible git submodules.  Unfortunately, manage_externals always wants to do the recursive check out of the inaccessible submodules, and there's no way (that I know of) to turn that off.
### Expected behavior and actual behavior:
There is currently no way to tell manage_externals (via Externals.cfg) that it should not do a recursive submodule checkout for a particular external.
### Steps to reproduce the problem (should include model description file(s) or link to publi c repository):
Look at the output of -h.  There is no Externals.cfg description option to do this.
### What is the changeset ID of the code, and the machine you are using:
I am using the manage_externals packaged with the ufs-srweather-app (https://github.com/ufs-community/ufs-srweather-app)
### have you modified the code? If so, it must be committed and available for testing:
No.
### Screen output or log file showing the error message and context:
N/A

**Comment by gold2718** [comment]
@christopherwharrop-noaa,
I apologize for what appears to be a deficiency in the documentation.
Can you try adding `externals = None` to the entry for the repository in question? That should prevent `checkout_externals` from attempting to load any sub externals (including git submodules).

Please report back so we know if this is a missing feature or a documentation bug.

**Comment by christopherwharrop-noaa** [comment]
@gold2718, 
Thank you for the pointer to that option.  I tested and it does indeed do exactly what I need.  I double checked the `-h` output and the `None` setting does not appear to be mentioned for the `externals` description option.  I think all that is needed is an update to the documentation, both in README and in the `-h` output.

**Comment by gold2718** [comment]
@christopherwharrop-noaa, I'm glad to hear that it works. I changed the title of this issue to make it clear that the documentation is deficient.
