### ISSUE TITLE
Tag name partially matching with branch results in error when checking out

### ISSUE THREAD

**Issue by jimmielin** [bandre-ucar/manage_externals#200]
### Summary of Issue:
If a Git source repository has both a tag and a branch name partially matching the tag name, e.g., tag `14.1.2` and branch `release/14.1.2`

The externals specification
```
[geoschem]
local_path = src/chemistry/geoschem/geoschem_src
protocol = git
repo_url = https://github.com/geoschem/geos-chem.git
tag = 14.1.2
required = True
```

will result in an error when checking out:
```
ERROR:root:In repo "geoschem": tag "14.1.2" is both a branch and a tag. git may checkout the branch instead of the tag depending on your version of git.
```

### Expected behavior and actual behavior:
The tag `14.1.2` should be checked out.

### Steps to reproduce the problem (should include model description file(s) or link to public repository):

1. Checkout ESCOMP/CESM
2. Modify CAM external to use repository `https://github.com/jimmielin/CAM` at `hash = 972c057e14c63a6e4a0cd5ec20d3ed66c6fe3c04`
3. Attempt to run `./manage_externals/checkout_externals`

The problematic external is under `components/cam/Externals_CAM.cfg` in `[geoschem]`.

We might be deleting this later to fix on our end.

The issue is due to `_is_unique_tag` check for `is_branch` uses
```python
is_branch = self._ref_is_branch(ref, remote_name, dirname)
```
which ends up calling `_git_lsremote_branch` that uses
```python
        cmd = ('git -C {dirname} ls-remote --exit-code --heads '
               '{remote_name} {ref}').format(
                   dirname=dirname, remote_name=remote_name, ref=ref).split()
```

This command will match the branch name "partially" (after the `/` separator)
```
$ git ls-remote --exit-code --heads origin 14.1.2
28345ee76e5631d6d14869a36dc73e9dd6e0ce1e        refs/heads/release/14.1.2
```
even though it is not intended, as there is a tag (`14.1.2`) that is the better match:
```
$ git show-ref --verify refs/tags/14.1.2 
28345ee76e5631d6d14869a36dc73e9dd6e0ce1e refs/tags/14.1.2
```

I'm not sure if there is a git convention that the branch names should not partially (last component after `/` separator) match tag names. We can fix it on our end but we wanted to confirm if it is intended behavior.

### have you modified the code? If so, it must be committed and available for testing:

No, this is the `manage_externals` provided in CESM master (`cesm2_3_alpha16f`)

On Derecho

### Screen output or log file showing the error message and context:

Please refer to above.

Copying @lizziel as well.

Thank you!

**Comment by jedwards4b** [comment]
Thank you for the detailed bug report.

**Comment by jedwards4b** [comment]
Please try: 

github.com:jedwards4b/manage_externals.git
 * [new branch]      partial_match -> partial_match

**Comment by jimmielin** [comment]
Thanks @jedwards4b, with the `partial_match` fix this case works correctly now with the debug output

```
geoschem, is_tag True is_branch False is_valid True
```

which is the expected behavior. Please feel free to close.
