### ISSUE TITLE
Add a version number that is accessible within the manage_externals code base

### ISSUE THREAD

**Issue by cacraigucar** [bandre-ucar/manage_externals#207]
### Summary of Issue:
Inside of the manage_externals structure, there is no apparent way to see what version of manage_externals is currently being used.  Either a flag --version to manage_externals or a file with the version information is requested.

**Comment by ekluzek** [comment]
I do support this, but I'm not sure the best way to implement it. 

Using "git describe" is only going to show the CESM, CAM, or CLM tag (or whatever top level setup is being used), so it's not useful.  As we saw today, you could use "git log" to parse the git hash, but how useful is the git hash for this functionality? Maybe if it also showed the date?

As such I think we'd need to save the tagname when tags are created to a file. That either means changing that file by hand, having a script to do it for you, or having that script trigged when tags are made. The last is probably the most robust, but might take some setup to do this well.

Just a few ideas from me...
