### ISSUE TITLE
Removal of svn support causes manage_externals to fail.

### ISSUE THREAD

**Issue by gold2718** [bandre-ucar/manage_externals#209]
### Summary of Issue:
Since the removal of svn support, any attempt to update a checkout from a version where any external has an svn sub-external will FAIL.

### Expected behavior and actual behavior:
Expect: Clean update of all externals to new tags
Actual:
```
$ ./manage_externals/checkout_externals 
Processing externals description file : Externals.cfg (/home/goldy/Projects/CESM)
Processing externals description file : Externals_CAM.cfg (/home/goldy/Projects/CESM/components/cam)
ERROR:root:SVN access to github.com is no longer supported

ERROR: SVN access to github.com is no longer supported
```
### Steps to reproduce the problem:
```
git clone https://github.com/ESCOMP/CESM
cd CESM
git checkout cesm2_3_alpha16h
./manage_externals/checkout_externals
git checkout master
./manage_externals/checkout_externals
```
### What is the changeset ID of the code, and the machine you are using:
See the changesets above
### have you modified the code? If so, it must be committed and available for testing:
No
### Screen output or log file showing the error message and context:
See 'actual behavior' section above.

**Comment by jedwards4b** [comment]
This is only true for svn access to github repositories.  svn access to svn repositories continues to work correctly.
I'm not sure I understand the purpose of opening this issue - the problem is that github has dropped support for this feature, there is nothing we can do in manage externals to fix it.

**Comment by gold2718** [comment]
I do not think that manage_externals needs to try to fix the lack of GitHub support for the svn bridge. However, the example I give is not asking manage_externals to check out an external with any `protocol=svn` entries. The situation is:
- I have a checkout of an external version _with_ `protocol=svn` entries.
- I want to update to a version _without_ `protocol=svn` entries.
- manage_externals refuses to do this, there is no way to update a checkout from an svn bridge version to a git sparse checkout version.
